### ISSUE TITLE
Version should be set by git tag

### ISSUE THREAD

**Issue by DirtyCajunRice** [itscontained/secret-manager#18]
I have the workflow properly working now, but the chart (and soon docker container) need to have their app version dictated by git tag. This will alleviate manual updating of in-code versioning.
Successful Workflow: https://github.com/itscontained/secret-manager/actions/runs/221652504

for the chart, i suggest setting `appVersion` to `0.0.0` and we can do a sed replace in the workflow
for the application, ldflags will let us inject 
```go
AppGitState  = ""
AppGitCommit = ""
AppVersion   = "canary"
```
via
```console
-X github.com/itscontained/secret-manager/pkg/util.AppVersion={.Version}
```

In addition, those 3 variables, if only referenced for version info below, do not need to be exportable.

**Comment by mcavoyk** [comment]
Some of that work for the binary is already done: https://github.com/itscontained/secret-manager/blob/master/Makefile#L15. The release process can either use a tag and have that be auto referenced or export a version environment variable to inject in the build.

Not quite sure how we want to version the build and the chart, should we have releases built both and have the versions be tied, or should we have build releases which can build both and then also ones which can just release the chart?

**Comment by DirtyCajunRice** [comment]
So the chart will more than likely iterate more than the app. Its "easy enough" to have github workflows check commit messages for "special words" and or changes specifically to the charts folder and build if the version changes. I do think it should automatically stamp a new chart when the app changes versions every time though.

**Comment by mcavoyk** [comment]
This should be closed with https://github.com/itscontained/secret-manager/pull/11.
The actual docker/helm build progress can be continued to track with https://github.com/itscontained/secret-manager/issues/19
