### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by c35sys** [itscontained/secret-manager#38]
Using [helm template README](https://github.com/itscontained/secret-manager/blob/master/deploy/charts/secret-manager/README.md.gotmpl), I tried to reach https://charts.itscontained.io without success.

Do you have an installation guide without helm ?

Sorry to open an issue, the [discord link](https://discord.com/eT6crpT) replies a 404.

**Comment by DirtyCajunRice** [comment]
@c35sys  Hey sorry for the late reply. `https://charts.itscontained.io` is not a viewable website. It is only a helm url. We are still working on our install docs for non-helm deployments. If you are trying to install it via manifests, let us know so we know what to add doc wise. 

Discord link https://discord.gg/eT6crpT

**Comment by c35sys** [comment]
Thanks, I managed to install it with Helm.

I created a PR to document it #40
