### ISSUE TITLE
Issue installing when installCRDs is set to true

### ISSUE THREAD

**Issue by devth** [itscontained/secret-manager#43]
```bash
helm upgrade -i secret-manager -f values.yaml itscontained/secret-manager
Release "secret-manager" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize
 "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

values.yaml
```yaml
installCRDs: true
```

K8S version
```bash
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

Any ideas? Is there a minimum k8s version required?

**Comment by devth** [comment]
It looks like 1.16+ is required.

My 1.12 cluster has `apiextensions.k8s.io/v1beta1` and CRDs were promoted to v1 as of 1.16: https://github.com/kubernetes/kubernetes/pull/79604

**Comment by DirtyCajunRice** [comment]
Correct. We do have the legacy CRDs available in the repo but are still working on some of the missing pieces of documentation that would have pointed you to the right place. For clusters < 1.16 you need to set to false and manually install the CRDs. Sorry for the confusion!

**Comment by devth** [comment]
Thanks. I'll submit a PR to update docs if you'd like.

**Comment by devth** [comment]
Apparently the legacy CRDs only work on 1.15+ clusters since they specify `preserveUnknownFields: false`.

On my 1.12 cluster this results in an error when trying to install the CRD:

```
error validating "secret-manager.itscontained.io_clustersecretstores.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by DirtyCajunRice** [comment]
@devth  1.12 was EOL 2019-07-08. Although this should technically work on 1.15+ do you have any reasoning on why we should support EOL cluster versions? [Reference](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md)

**Comment by devth** [comment]
Nope, but at least putting the above out in the open might help someone else, or me 2 weeks from now.

For various reasons I am stuck on a 1.12 cluster for at least another month 😱 .

**Comment by devth** [comment]
I wonder if there's any convention in Helm or elsewhere for specifying minimum K8S version. Then at least it'd be explicit.

**Comment by DirtyCajunRice** [comment]
Explicit "expected minimum" for sure can be added to docs as well as a hard "no" in the helm chart for below them - no arguments there. 

As for the convention, helm binaries have [a page](https://helm.sh/docs/topics/version_skew/#:~:text=2%20client%2C%20so%20it%20is,n%2D1%20versions%20of%20Kubernetes.) that specify what its expected to work with. The chart itself could just put a check in `_helpers.tpl` that does a check like...
```go
{{- if and (semverCompare ">= 1.15.0 < 1.16.0" .Capabilities.KubeVersion.GitVersion) .Values.installCRDs -}}
  {{- fail "Kubernetes 1.15.x clusters must manually install the legacy CRDs" -}}
{{- else if semverCompare "< 1.15.0" .Capabilities.KubeVersion.GitVersion -}}
  {{- fail "Kubernetes versions prior to 1.15.x are not supported" -}}
{{- end }}
```

**Comment by mcavoyk** [comment]
Re-opening this, should be able to generate legacy crd's which work with v1.11-v1.15 (although these will have less functionality) with the controller-gen option `crd:trivialVersions=true`
