### ISSUE TITLE
Fix multi-arch docker build

### ISSUE THREAD

**Issue by mcavoyk** [itscontained/secret-manager#47]
Build/push pipeline seems broken, looks like the base image didn't have explicit multi-arch support, but worked because the image manifest didn't specify architecture and has no binaries, so effectively supported arm without needing different images per arch.

I think the choice for today is either drop arm/v7 until https://github.com/GoogleContainerTools/distroless/issues/377 is closed, or continue using the previous image (now available under `gcr.io/distroless/static:nonroot-amd64` rather than `gcr.io/distroless/static:nonroot`)

**Comment by DirtyCajunRice** [comment]
Currently using the second option per earlier cleanup. Can switch back once above is addressed
