### ISSUE TITLE
RBAC Issue - ClusterRole Colliding - when installing the helm chart multiple times

### ISSUE THREAD

**Issue by huguesalary** [itscontained/secret-manager#60]
**Describe the bug**:

Installing the chart multiple times on the same cluster isn't possible because of the ClusterRoles colliding.

Given 2 namespace:
- ns1 
- ns2

Running:

```
helm install --namespace ns1 secret-manager itscontained/secret-manager --set namespace=ns1
helm install --namespace ns2 secret-manager itscontained/secret-manager --set namespace=ns2
```

The first install will work.

The second install will fail:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "secret-manager-controller" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "ns2": current value is "ns1"
```

**Expected behavior**

The helm chart should be deployable multiple times on the same cluster and cluster-roles shouldn't collide.

**Steps to reproduce the bug**:

```
helm install --namespace ns1 secret-manager itscontained/secret-manager --set namespace=ns1
helm install --namespace ns2 secret-manager itscontained/secret-manager --set namespace=ns2
```

**Anything else we should know?**

Nope, other than I appreciate the work put in maintaining this open source project.

**Environment details:**:
- Kubernetes version (e.g. v1.18.9): 1.18
- Secret-Manager version (e.g. v0.2.0): the one deployed by the helm chart 0.1.2
- Install method (e.g. helm or static manifests): Helm

/kind bug

**Comment by mcavoyk** [comment]
This is pretty usual for charts which require cluster scoped resources (ex. [cluster-autoscaler](https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-chart-1.1.0/charts/cluster-autoscaler-chart/templates/clusterrole.yaml#L7)).

Either helm release name should be different, or `fullnameOverride` can be used to change the full name of resources to another name. 

Another solution specific to this project would be to install the controller once, and use ClusterSecretStore or SecretStore's to namespace the authentication secrets needed for using ExternalSecrets.

**Comment by huguesalary** [comment]
My bad! The release name should indeed be different. With different release names, this works as expected.
